# Generated by Django 4.0.4 on 2022-06-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receta_3a6',
            new_name='receta_4a6',
        ),
        migrations.RenameModel(
            old_name='receta_6a10',
            new_name='receta_7a10',
        ),
    ]
