# Generated by Django 4.0.4 on 2022-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_rename_receta_3a6_receta_4a6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta_1a3',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='receta_4a6',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='receta_7a10',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='receta_1a3',
            name='cantidad_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_1a3',
            name='cantidad_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_1a3',
            name='cantidad_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_1a3',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receta_4a6',
            name='cantidad_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_4a6',
            name='cantidad_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_4a6',
            name='cantidad_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_4a6',
            name='cantidad_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_4a6',
            name='cantidad_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_4a6',
            name='cantidad_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_4a6',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='cantidad_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta_7a10',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receta_1a3',
            name='ingrediente_1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_1a3',
            name='ingrediente_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_1a3',
            name='ingrediente_3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_4a6',
            name='ingrediente_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_4a6',
            name='ingrediente_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_4a6',
            name='ingrediente_3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_4a6',
            name='ingrediente_4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_4a6',
            name='ingrediente_5',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_4a6',
            name='ingrediente_6',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_10',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_5',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_6',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_7',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_8',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='ingrediente_9',
            field=models.CharField(max_length=30),
        ),
    ]
