# Generated by Django 4.0.4 on 2022-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_remove_receta_1a3_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta_1a3',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='receta_4a6',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='receta_7a10',
            name='procedimiento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
