# Generated by Django 4.0.4 on 2022-06-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_receta_1a3_procedimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta_1a3',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='receta_4a6',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='receta_7a10',
            old_name='nombre',
            new_name='name',
        ),
    ]
